### ISSUE TITLE
Nuclei Studio 2023.10 Qemu Debug Configuration RVV Length not passed in qemu command line

### ISSUE THREAD

**Issue by fanghuaqi** [Nuclei-Software/nuclei-studio#12]
Qemu 调试页面下 使能了v扩展，且更新了 RVV length，也不会传递。

![企业微信截图_16998734632265](https://github.com/Nuclei-Software/nuclei-studio/assets/1538922/f41ce69a-f4e7-46cf-8375-b7db47f17511)

**Comment by laomaolaile** [comment]
This bug has been fixed in Nuclei Studio 2023.10，https://github.com/Nuclei-Software/nuclei-studio/blob/main/7-update_nucleistudio_202310_to_fixed_version.md
