### ISSUE TITLE
Display items order error when creating nuclei project

### ISSUE THREAD

**Issue by YourDecesion** [Nuclei-Software/nuclei-studio#25]
Each time when I try to create a dhrystone example project，"Creating Nuclei RISC-V C/C++ project" window will display a different item order as below pictures show.
<img width="266" alt="display1" src="https://github.com/Nuclei-Software/nuclei-studio/assets/145883454/ad53a58d-1d5a-4bf2-8c72-06510cfe3d6f">
<img width="266" alt="display2" src="https://github.com/Nuclei-Software/nuclei-studio/assets/145883454/d121d285-6161-497a-aaca-76accafeeaf8">
<img width="266" alt="display3" src="https://github.com/Nuclei-Software/nuclei-studio/assets/145883454/4ea73271-19a5-4fb7-83a6-f2e126b6e015">
<img width="266" alt="display4" src="https://github.com/Nuclei-Software/nuclei-studio/assets/145883454/0d15badf-a97e-4146-b6a9-850a8f767995">

**Comment by fanghuaqi** [comment]
@dongchen1221 Take a look

**Comment by fanghuaqi** [comment]
It didn't affect the function, but we will take a look at it @YourDecesion, thanks for your report.
