### ISSUE TITLE
In the 2024.02.DEV version, when importing an external project, there is an issue with abnormal saving of the download/linker script.

### ISSUE THREAD

**Issue by laomaolaile** [Nuclei-Software/nuclei-studio#30]
In the 2024.02.DEV version, when importing an external project and attempting to modify the download/linker script values in the Nuclei Setting, there is an issue with abnormal saving. The changes made to the script cannot be correctly saved, and the Nuclei Setting is displayed incompletely. However, this problem does not occur in newly created projects.

![image](https://github.com/Nuclei-Software/nuclei-studio/assets/19726057/e098889f-e619-444e-aa0a-eacbec48763a)

**Comment by laomaolaile** [comment]
The issue arises because when Nuclei Setting attempts to read the project configuration, it searches for the project directory and files within the current workspace. However, when importing a project, even though the project appears to be within the current workspace, the actual project files might be located in a different directory. This can cause the IDE to be unable to correctly locate and read the project files and configurations.

To avoid this problem, it is recommended to tick the "Copy projects into workspace" option during the import process. By doing so, the IDE will copy the project files into the designated workspace directory, ensuring that all necessary files and configurations are accessible and readable by the IDE.

![image](https://github.com/Nuclei-Software/nuclei-studio/assets/19726057/64ebe7ff-c7da-458b-b21e-51d50946b478)

This issue will be addressed and fixed in subsequent versions to improve the user experience and ensure smoother project imports.

**Comment by fanghuaqi** [comment]
Is it be fixed in 2024.06 @laomaolaile
