### ISSUE TITLE
202406版本，在 ARM 的 WIN11上会出现打开后卡死无响应的问题

### ISSUE THREAD

**Issue by bigfish666** [Nuclei-Software/nuclei-studio#35]
之前的版本都没有遇到此问题，升级后打开会卡死，右下角的状态是 setup check。完全删掉，重新安装也不行，还是会软件无响应。

**Comment by laomaolaile** [comment]
能否提供截图或者更详细的信息

**Comment by laomaolaile** [comment]
您是从官网上下载的最新版本么？能否提供一下截图或者更多的信息

**Comment by bigfish666** [comment]
是官网下载的最新版本。大概的状态是这样。然后
![Uploading image.png…]()

**Comment by laomaolaile** [comment]
截图看不到，日志里无法确认哪一步出问题了

**Comment by bigfish666** [comment]
![Uploading WX20240807-154235.png…]()

截图上传不上去。就是程序未响应的一个截图。我是在configuration 目录下查看的log。还有哪个地方能看到更细节的 Log 吗？

**Comment by fanghuaqi** [comment]
这个估计是Eclipse IDE 2024.06带来的问题 https://github.com/eclipse-platform/eclipse.platform.swt/issues/1252#issuecomment-2168274114

**Comment by bigfish666** [comment]
> 这个估计是Eclipse IDE 2024.06带来的问题 [eclipse-platform/eclipse.platform.swt#1252 (comment)](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1252#issuecomment-2168274114)

看上去这个问题是支持的老版本的问题，我现在是 win11的环境，理论上应该没有类似的问题。我现在回退到02版本是完全没有问题的。刚才又尝试了一下，升级到06版本后，重启电脑，新建一个工作区是可以使用的。但是一旦关闭了 nuclei studio 再打开，进入到刚才的工程，就会遇到之前的卡死无响应的问题。有没有可能新版本的 eclipse 需要某一个环境，而我的电脑不具备？

**Comment by fanghuaqi** [comment]
> 有没有可能新版本的 eclipse 需要某一个环境，而我的电脑不具备？

可以比较容易的做一个验证，你可以下载 https://www.eclipse.org/downloads/packages/release/2024-06/r/eclipse-ide-cc-developers 一个单独的 Eclipse 2024-06的IDE试下 Windows [x86_64](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2024-06/R/eclipse-cpp-2024-06-R-win32-x86_64.zip)

**Comment by bigfish666** [comment]
> > 有没有可能新版本的 eclipse 需要某一个环境，而我的电脑不具备？
> 
> 可以比较容易的做一个验证，你可以下载 https://www.eclipse.org/downloads/packages/release/2024-06/r/eclipse-ide-cc-developers 一个单独的 Eclipse 2024-06的IDE试下 Windows [x86_64](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2024-06/R/eclipse-cpp-2024-06-R-win32-x86_64.zip)

我下载了 eclipse 2024 -06测试了一下，问题也会复现。后来弹出了下面的提醒，我更新了 JDK 的版本到最新的21后，问题好像消失了。我自己测试了几次，关闭软件重开，重启再打开 nucleistuio 都没有再复现。
https://www.eclipse.org/setups/sponsor/?scope=Eclipse%20IDE%20for%20C/C%2B%2B%20Developers%20(includes%20Incubating%20components)&version=4.32.0.20240606-0749&campaign=2024-06

**Comment by fanghuaqi** [comment]
> 我下载了 eclipse 2024 -06测试了一下，问题也会复现。后来弹出了下面的提醒，我更新了 JDK 的版本到最新的21后，问题好像消失了。我自己测试了几次，关闭软件重开，重启再打开 nucleistuio 都没有再复现。

@laomaolaile 你看看这个, 我们应该已经内建了JDK在IDE里面的，可以确认下是哪个版本

**Comment by fanghuaqi** [comment]
我看了下我们里面已经有了 `NucleiStudio\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_21.0.3.v20240426-1530\jre` @bigfish666 

且 `NucleiStudio.ini`里面配置如下

~~~
-vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_21.0.3.v20240426-1530/jre/bin
-vmargs
-Dorg.eclipse.ecf.provider.filetransfer.excludeContributors=org.eclipse.ecf.provider.filetransfer.httpclientjava
~~~

**Comment by bigfish666** [comment]
> 我看了下我们里面已经有了 `NucleiStudio\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_21.0.3.v20240426-1530\jre` @bigfish666
> 
> 且 `NucleiStudio.ini`里面配置如下
> 
> ```
> -vm
> plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_21.0.3.v20240426-1530/jre/bin
> -vmargs
> -Dorg.eclipse.ecf.provider.filetransfer.excludeContributors=org.eclipse.ecf.provider.filetransfer.httpclientjava
> ```

我看到了 plugins 里确实有，但是我下载了最新的 jdk 21.0.4+7，在系统环境变量里配置了默认的 jdk，然后把'NucleiStudio.ini`配置成本地的 jdk 路径包，解决了。我的情况可能特殊，我是在 mac 下的 parallel 环境下运行的arm 版 win11。有可能我是个例。

**Comment by laomaolaile** [comment]
NucleiStudio中内嵌了jre 是 21.0.3版本

![image](https://github.com/user-attachments/assets/5b0b6f23-68d2-4d1d-b2f7-8aeb37192ed6)

并且在NucleiStudio.ini指定vm是用的这个jre，按理说跟本机jre没有关系

![image](https://github.com/user-attachments/assets/7f3405f7-c8e1-48be-9b13-db0187b1602c)

请确认一下这个配置都是对的么？或者修改这个配置，指向您本机的jre，以确认一下确实是jre的问题

或者有没有可能是内嵌的jre在您的系统上无法运行？

**Comment by laomaolaile** [comment]
有两个地方可以查看日志

workspace\.metadata\ 下有系统运行日志

NucleiStudio\configuration\ 有插件运运的日志

这两个地方的日志都能帮助分析IDE的问题，如果方便，可以提供一下这两个地方的日志，帮助我们改进和优化，谢谢

**Comment by bigfish666** [comment]
[1723088155281.log](https://github.com/user-attachments/files/16537253/1723088155281.log)
[metadata.log](https://github.com/user-attachments/files/16537285/metadata.log)
我上传了两个 Log。我测试了一下，把vm 后面的地址替换成默认的后，现象重新出现。卡死在 setup check 阶段。
-vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_21.0.3.v20240426-1530/jre/bin

**Comment by fanghuaqi** [comment]
> 把vm 后面的地址替换成默认的后，现象重新出现。卡死在 setup check 阶段。

能提供下你自己下载的vm是啥么，下载链接？ @bigfish666

**Comment by bigfish666** [comment]
> > 把vm 后面的地址替换成默认的后，现象重新出现。卡死在 setup check 阶段。
> 
> 能提供下你自己下载的vm是啥么，下载链接？ @bigfish666

https://adoptium.net/.
下载链接如上，版本就是这个**OpenJDK21U-jdk_x64_windows_hotspot_21.0.4_7**
我尝试在软件内更新一下 ,通过之前提到的 eclipse 的那个弹窗的网页，
把 plugins 的版本更新到plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_21.0.4.v20240802-1551/jre/bin，然后 -vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_21.0.4.v20240802-1551/jre/bin
替换原来我设置的本地的 jdk 21.0.4+7路径。使用新更新后的plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_21.0.4.v20240802-1551/jre/bin路径同样不会出现卡死无响应的问题。

**Comment by bigfish666** [comment]
但是现在遇到一个新问题是编译完成后，使用 JLINK调试会报错。。
Error in services launch sequence
Launching command [C:\Program Files (Arm)\SEGGER/JLinkGDBServerCL.exe -if jtag -device CC2560A -endian little -speed auto -port 2331 -swoport 2332 -telnetport 2333 -vd -ir -localhostonly 1 -singlerun -strict -timeout 0 -nogui] failed.
Launching command [C:\Program Files (Arm)\SEGGER/JLinkGDBServerCL.exe -if jtag -device CC2560A -endian little -speed auto -port 2331 -swoport 2332 -telnetport 2333 -vd -ir -localhostonly 1 -singlerun -strict -timeout 0 -nogui] failed.
Cannot run program "C:\Program Files (Arm)\SEGGER/JLinkGDBServerCL.exe": Launching failed
感觉是新的 jdk 的版本还有哪不兼容，打不开 JlinkGDBServer。我回退到02版本就好了。可以正常调试。

**Comment by fanghuaqi** [comment]
建议还是找个正常的Windows 10/11 64bit for Intel/AMD的电脑。你这个环境我们也没有。。 

当然你也可以向 https://github.com/eclipse-platform/eclipse.platform/issues 反馈下Eclipse IDE 2024.06的问题。

**Comment by bigfish666** [comment]
> 建议还是找个正常的Windows 10/11 64bit for Intel/AMD的电脑。你这个环境我们也没有。。
> 
> 当然你也可以向 https://github.com/eclipse-platform/eclipse.platform/issues 反馈下Eclipse IDE 2024.06的问题。

嗯好的，感谢支持。

**Comment by bigfish666** [comment]
最后再反馈的信息，更新了新的jdk 版本后不能JLINK调试的原因是工作区还是老版本建立的，重新建立一个新的，导入工程可以正常编译调试。
