### ISSUE TITLE
Build fail when using pre- and post-steps in Nuclei Studio 2023.10

### ISSUE THREAD

**Issue by fanghuaqi** [Nuclei-Software/nuclei-studio#6]
See

- [在编译工程时，使用了Pre-build Command/Post-build Command时报错](https://github.com/Nuclei-Software/nuclei-studio/blob/main/4-use_pre_build_or_post_build.md#%E5%9C%A8%E7%BC%96%E8%AF%91%E5%B7%A5%E7%A8%8B%E6%97%B6%E4%BD%BF%E7%94%A8%E4%BA%86pre-build-commandpost-build-command%E6%97%B6%E6%8A%A5%E9%94%99)
- https://github.com/eclipse-embed-cdt/eclipse-plugins/issues/597

> This issue is caused by the busybox used by us internally distribute an make utils, which is not working for us, see https://github.com/eclipse-embed-cdt/eclipse-plugins/issues/597#issuecomment-1809731807

Just replace the `toolchain/build-tools` folder content with [win32-buildtools-1.2.zip](https://github.com/Nuclei-Software/nuclei-studio/files/13363451/win32-buildtools-1.2.zip) which is based on https://github.com/xpack-dev-tools/windows-build-tools-xpack/releases/tag/v4.4.1-2

This issue will be solved

**Comment by laomaolaile** [comment]
This bug has been fixed in Nuclei Studio 2023.10，https://github.com/Nuclei-Software/nuclei-studio/blob/main/7-update_nucleistudio_202310_to_fixed_version.md
